#!/usr/bin/env node

/**
 * Build Configuration Script
 * Reads environment variables and generates config.js for the application
 * Run this script before deploying: node build-config.js
 */

const fs = require('fs');
const path = require('path');

// Load .env file if it exists
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
            const [key, ...valueParts] = trimmed.split('=');
            const value = valueParts.join('=');
            if (key && value) {
                process.env[key] = value;
            }
        }
    });
}

// Read environment variables
const config = {
    streams: {
        1: process.env.STREAM_URL_LOUNGE || '',
        2: process.env.STREAM_URL_COOL || '',
        3: process.env.STREAM_URL_ROCK || '',
        4: process.env.STREAM_URL_PARTY || '',
        5: process.env.STREAM_URL_CHILL || ''
    },
    channels: {
        1: process.env.CHANNEL_ID_LOUNGE || '',
        2: process.env.CHANNEL_ID_COOL || '',
        3: process.env.CHANNEL_ID_ROCK || '',
        4: process.env.CHANNEL_ID_PARTY || '',
        5: process.env.CHANNEL_ID_CHILL || ''
    },
    live: {
        streamEndpoint: process.env.LIVE_STREAM_ENDPOINT || '',
        webrtcSignalingServer: process.env.LIVE_WEBRTC_SIGNALING_SERVER || '',
        storageKey: process.env.LIVE_STORAGE_KEY || 'vicetream_live_status'
    }
};

// Generate config.js file
const configContent = `// Auto-generated configuration file
// DO NOT EDIT MANUALLY - Generated by build-config.js
// Generated at: ${new Date().toISOString()}

const CONFIG = ${JSON.stringify(config, null, 2)};

// Export for use in modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
`;

const outputPath = path.join(__dirname, 'config.js');
fs.writeFileSync(outputPath, configContent, 'utf8');

console.log('✅ Configuration file generated successfully!');
console.log(`📁 Output: ${outputPath}`);

// Validate that all required URLs are present
const missingVars = [];
Object.entries(config.streams).forEach(([key, value]) => {
    if (!value) missingVars.push(`STREAM_URL for station ${key}`);
});
Object.entries(config.channels).forEach(([key, value]) => {
    if (!value) missingVars.push(`CHANNEL_ID for station ${key}`);
});

if (missingVars.length > 0) {
    console.warn('\n⚠️  Warning: Missing environment variables:');
    missingVars.forEach(v => console.warn(`   - ${v}`));
    console.warn('\nCheck your .env file and make sure all variables are set.');
}
