(function() {
    'use strict';
    
    // ==========================================================================
    // Configuration - Loaded from environment variables
    // ==========================================================================
    
    // CONFIG_PLACEHOLDER_START - Auto-injected by build-config.js
    var CONFIG = JSON.parse(atob('eyJzdHJlYW1zIjp7IjEiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS9ncm9vdmVzYWxhZC0xMjgtbXAzIiwiMiI6Imh0dHA6Ly9saXN0ZW4uYWNjdXJhZGlvLmNvbTo4MC8xMDAtZ3JlYXRlc3Qtcm9jay1ndWl0YXItc29uZ3MiLCIzIjoiaHR0cHM6Ly9pY2UxLnNvbWFmbS5jb20vYmVhdGJsZW5kZXItMTI4LW1wMyIsIjQiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS9kcm9uZXpvbmUtMTI4LW1wMyIsIjUiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS83c291bC0xMjgtbXAzIiwiNiI6Imh0dHBzOi8vaWNlMS5zb21hZm0uY29tL2Jvc3NhLTEyOC1tcDMifSwiY2hhbm5lbHMiOnsiMSI6Imdyb292ZXNhbGFkIiwiMiI6IjEwMC1ncmVhdGVzdC1yb2NrLWd1aXRhci1zb25ncyIsIjMiOiJiZWF0YmxlbmRlciIsIjQiOiJkcm9uZXpvbmUiLCI1IjoiN3NvdWwiLCI2IjoiYm9zc2EifSwibGl2ZSI6eyJzdHJlYW1FbmRwb2ludCI6Imh0dHBzOi8veW91ci1zdHJlYW1pbmctc2VydmVyLmNvbS9saXZlIiwid2VicnRjU2lnbmFsaW5nU2VydmVyIjoid3NzOi8veW91ci1zaWduYWxpbmctc2VydmVyLmNvbSIsInN0b3JhZ2VLZXkiOiJ2aWNldHJlYW1fbGl2ZV9zdGF0dXMifX0='));
    // CONFIG_PLACEHOLDER_END
    
    // Station configuration will be loaded from CONFIG object (generated by build-config.js)
    var stations = [];
    
    // Initialize stations from CONFIG if available
    function initializeStations() {
        if (typeof CONFIG !== 'undefined' && CONFIG.streams && CONFIG.channels) {
            stations = [
                { 
                    name: 'Lounge', 
                    theme: 'lounge',
                    channel: CONFIG.channels[1],
                    url: CONFIG.streams[1]
                },
                { 
                    name: 'Rock', 
                    theme: 'rock',
                    channel: CONFIG.channels[2],
                    url: CONFIG.streams[2]
                },
                { 
                    name: 'Party', 
                    theme: 'party',
                    channel: CONFIG.channels[3],
                    url: CONFIG.streams[3]
                },
                { 
                    name: 'Chill', 
                    theme: 'chill',
                    channel: CONFIG.channels[4],
                    url: CONFIG.streams[4]
                },
                { 
                    name: 'Funky', 
                    theme: 'funky',
                    channel: CONFIG.channels[5],
                    url: CONFIG.streams[5]
                },
                { 
                    name: 'Bossa', 
                    theme: 'bossa',
                    channel: CONFIG.channels[6],
                    url: CONFIG.streams[6]
                }
            ];
        } else {
            console.error('CONFIG not found. Please run build-config.js to generate configuration.');
            // Fallback to empty stations - will need config to work
            stations = [
                { name: 'Lounge', theme: 'lounge', channel: '', url: '' },
                { name: 'Rock', theme: 'rock', channel: '', url: '' },
                { name: 'Party', theme: 'party', channel: '', url: '' },
                { name: 'Chill', theme: 'chill', channel: '', url: '' },
                { name: 'Funky', theme: 'funky', channel: '', url: '' },
                { name: 'Bossa', theme: 'bossa', channel: '', url: '' }
            ];
        }
    }
    
    var METADATA_UPDATE_INTERVAL = 5000; // 5 seconds
    
    // ==========================================================================
    // State
    // ==========================================================================
    
    var currentStationIndex = 0;
    var isPlaying = false;
    var audioElement = null;
    var metadataInterval = null;
    var currentTrack = { title: '', artist: '' };
    
    // ==========================================================================
    // DOM References (cached after init)
    // ==========================================================================
    
    var elements = {
        playBtn: null,
        stationName: null,
        trackTitle: null,
        trackArtist: null,
        trackInfo: null,
        floppyDisks: null,
        html: null
    };
    
    // ==========================================================================
    // Theme Management
    // ==========================================================================
    
    function setTheme(themeName) {
        elements.html.setAttribute('data-theme', themeName);
    }
    
    function updateActiveState(index) {
        // Remove active class from all disks
        elements.floppyDisks.forEach(function(disk) {
            disk.classList.remove('active');
        });
        
        // Add active class to selected disk
        if (elements.floppyDisks[index]) {
            elements.floppyDisks[index].classList.add('active');
        }
        
        // Update station name display
        if (elements.stationName) {
            elements.stationName.textContent = stations[index].name;
        }
        
        // Update theme
        setTheme(stations[index].theme);
    }
    
    // ==========================================================================
    // Metadata Fetching (SomaFM API)
    // ==========================================================================
    
    function fetchMetadata() {
        var station = stations[currentStationIndex];
        
        // Skip metadata fetching if no channel ID
        if (!station.channel) {
            console.log('No channel ID for this station - skipping metadata fetch');
            updateTrackDisplay('Now Playing', station.name);
            return;
        }
        
        // Detect source type and fetch accordingly
        if (station.url.includes('internet-radio.com')) {
            fetchInternetRadioMetadata(station);
        } else if (station.url.includes('somafm.com')) {
            fetchSomaFMMetadata(station);
        } else if (station.url.includes('accuradio.com')) {
            fetchAccuRadioMetadata(station);
        } else {
            // Generic fallback
            updateTrackDisplay('Now Playing', station.name);
        }
    }
    
    function fetchSomaFMMetadata(station) {
        var apiUrl = 'https://somafm.com/songs/' + station.channel + '.json';
        
        fetch(apiUrl)
            .then(function(response) {
                if (!response.ok) throw new Error('Network response was not ok');
                return response.json();
            })
            .then(function(data) {
                if (data && data.songs && data.songs.length > 0) {
                    var song = data.songs[0]; // Most recent song
                    updateTrackDisplay(song.title, song.artist);
                }
            })
            .catch(function(error) {
                console.warn('Failed to fetch SomaFM metadata:', error);
            });
    }
    
    function fetchInternetRadioMetadata(station) {
        // Fetch from internet-radio.com station page using CORS proxy
        var stationUrl = 'https://www.internet-radio.com/station/' + station.channel + '/';
        
        // List of CORS proxies to try (in order)
        var corsProxies = [
            'https://corsproxy.io/?',
            'https://api.allorigins.win/raw?url=',
            'https://api.codetabs.com/v1/proxy?quest='
        ];
        
        var proxyIndex = 0;
        
        function tryFetchWithProxy() {
            if (proxyIndex >= corsProxies.length) {
                console.error('All CORS proxies failed for internet-radio.com');
                updateTrackDisplay('Now Playing', station.name);
                return;
            }
            
            var corsProxy = corsProxies[proxyIndex];
            var proxiedUrl = corsProxy + encodeURIComponent(stationUrl);
            
            console.log('Trying CORS proxy #' + (proxyIndex + 1) + ':', proxiedUrl);
            
            fetch(proxiedUrl, { timeout: 10000 })
                .then(function(response) {
                    console.log('Response status:', response.status);
                    if (!response.ok) throw new Error('Network response was not ok: ' + response.status);
                    return response.text();
                })
                .then(function(html) {
                    console.log('Received HTML, length:', html.length);
                    
                    // Try multiple parsing methods
                    
                    // Method 1: Look for the "Now Playing" text pattern in markdown format
                    var nowPlayingMatch = html.match(/Now Playing\s*:\s*\*\*([^*]+)\*\*/);
                    
                    if (nowPlayingMatch && nowPlayingMatch[1]) {
                        console.log('Found match (Method 1):', nowPlayingMatch[1]);
                        parseAndDisplayTrack(nowPlayingMatch[1].trim(), station.name);
                        return;
                    }
                    
                    // Method 2: Parse HTML and look in the page
                    var parser = new DOMParser();
                    var doc = parser.parseFromString(html, 'text/html');
                    var bodyText = doc.body.textContent || doc.body.innerText || '';
                    
                    // Try different patterns
                    var patterns = [
                        /Now Playing\s*:\s*\*\*([^*]+)\*\*/,
                        /Now Playing\s*:\s*([^\n]+)/i,
                        /playing[:\s]+([^\n]+)/i
                    ];
                    
                    for (var i = 0; i < patterns.length; i++) {
                        var match = bodyText.match(patterns[i]);
                        if (match && match[1]) {
                            console.log('Found match (Method 2, pattern ' + i + '):', match[1]);
                            parseAndDisplayTrack(match[1].trim(), station.name);
                            return;
                        }
                    }
                    
                    console.warn('Could not find "Now Playing" in response');
                    updateTrackDisplay('Now Playing', station.name);
                })
                .catch(function(error) {
                    console.error('CORS proxy #' + (proxyIndex + 1) + ' failed:', error);
                    // Try next proxy
                    proxyIndex++;
                    setTimeout(tryFetchWithProxy, 1000); // Wait 1 second before trying next proxy
                });
        }
        
        tryFetchWithProxy();
    }
    
    function fetchAccuRadioMetadata(station) {
        // Fetch from AccuRadio page using CORS proxy
        var pageUrl = 'https://www.accuradio.com/classic-rock/';
        
        // List of CORS proxies to try (in order)
        var corsProxies = [
            'https://corsproxy.io/?',
            'https://api.allorigins.win/raw?url=',
            'https://api.codetabs.com/v1/proxy?quest='
        ];
        
        var proxyIndex = 0;
        
        function tryFetchWithProxy() {
            if (proxyIndex >= corsProxies.length) {
                console.error('All CORS proxies failed for AccuRadio');
                updateTrackDisplay('Now Playing', station.name);
                return;
            }
            
            var corsProxy = corsProxies[proxyIndex];
            var proxiedUrl = corsProxy + encodeURIComponent(pageUrl);
            
            console.log('Trying CORS proxy #' + (proxyIndex + 1) + ' for AccuRadio:', proxiedUrl);
            
            fetch(proxiedUrl, { timeout: 10000 })
                .then(function(response) {
                    console.log('AccuRadio response status:', response.status);
                    if (!response.ok) throw new Error('Network response was not ok: ' + response.status);
                    return response.text();
                })
                .then(function(html) {
                    console.log('Received AccuRadio HTML, length:', html.length);
                    
                    // Parse HTML and look for now playing info
                    var parser = new DOMParser();
                    var doc = parser.parseFromString(html, 'text/html');
                    
                    // Try to find song info in various places
                    var songTitle = doc.querySelector('.song-title, .now-playing-title, [class*="song"]');
                    var songArtist = doc.querySelector('.song-artist, .now-playing-artist, [class*="artist"]');
                    
                    if (songTitle && songArtist) {
                        var title = songTitle.textContent.trim();
                        var artist = songArtist.textContent.trim();
                        console.log('Found AccuRadio metadata - Artist:', artist, 'Title:', title);
                        updateTrackDisplay(title, artist);
                        return;
                    }
                    
                    // Fallback: Try to parse from body text
                    var bodyText = doc.body.textContent || doc.body.innerText || '';
                    var patterns = [
                        /Now Playing[:\s]+([^-]+)\s*-\s*([^\n]+)/i,
                        /([A-Z][^-]+)\s*-\s*([A-Z][^\n]+)/
                    ];
                    
                    for (var i = 0; i < patterns.length; i++) {
                        var match = bodyText.match(patterns[i]);
                        if (match && match[1] && match[2]) {
                            console.log('Found AccuRadio match (pattern ' + i + '):', match[1], '-', match[2]);
                            updateTrackDisplay(match[2].trim(), match[1].trim());
                            return;
                        }
                    }
                    
                    console.warn('Could not find now playing info in AccuRadio response');
                    updateTrackDisplay('100 Greatest Rock Guitar Songs', station.name);
                })
                .catch(function(error) {
                    console.error('AccuRadio CORS proxy #' + (proxyIndex + 1) + ' failed:', error);
                    // Try next proxy
                    proxyIndex++;
                    setTimeout(tryFetchWithProxy, 1000); // Wait 1 second before trying next proxy
                });
        }
        
        tryFetchWithProxy();
    }
    
    function parseAndDisplayTrack(trackInfo, stationName) {
        // Remove any markdown or HTML formatting
        trackInfo = trackInfo.replace(/\*\*/g, '').replace(/<[^>]+>/g, '').trim();
        
        // Split by common separators: " - ", " – ", " — "
        var parts = trackInfo.split(/\s*[-–—]\s*/);
        
        if (parts.length >= 2) {
            var artist = parts[0].trim();
            var title = parts.slice(1).join(' - ').trim();
            console.log('Parsed - Artist:', artist, 'Title:', title);
            updateTrackDisplay(title, artist);
        } else {
            console.log('Could not split track info:', trackInfo);
            updateTrackDisplay(trackInfo, stationName);
        }
    }
    
    function updateTrackDisplay(title, artist) {
        // Only update if something changed
        if (title === currentTrack.title && artist === currentTrack.artist) {
            return;
        }
        
        currentTrack.title = title || '';
        currentTrack.artist = artist || '';
        
        if (elements.trackTitle) {
            elements.trackTitle.textContent = currentTrack.title || '—';
            // Add animation class
            elements.trackTitle.classList.remove('track-update');
            void elements.trackTitle.offsetWidth; // Trigger reflow
            elements.trackTitle.classList.add('track-update');
        }
        
        if (elements.trackArtist) {
            elements.trackArtist.textContent = currentTrack.artist;
            elements.trackArtist.classList.remove('track-update');
            void elements.trackArtist.offsetWidth;
            elements.trackArtist.classList.add('track-update');
        }
        
        // Update page title with now playing
        if (isPlaying && currentTrack.title) {
            document.title = currentTrack.title + ' - ' + stations[currentStationIndex].name + ' | Vicetream';
        }
    }
    
    function clearTrackDisplay() {
        currentTrack = { title: '', artist: '' };
        if (elements.trackTitle) {
            elements.trackTitle.textContent = '—';
        }
        if (elements.trackArtist) {
            elements.trackArtist.textContent = '';
        }
        document.title = 'Vicetream Tunes';
    }
    
    function startMetadataUpdates() {
        // Fetch immediately
        fetchMetadata();
        
        // Then fetch periodically
        if (metadataInterval) {
            clearInterval(metadataInterval);
        }
        metadataInterval = setInterval(fetchMetadata, METADATA_UPDATE_INTERVAL);
    }
    
    function stopMetadataUpdates() {
        if (metadataInterval) {
            clearInterval(metadataInterval);
            metadataInterval = null;
        }
    }
    
    // ==========================================================================
    // Audio Playback
    // ==========================================================================
    
    function updatePlayButton(playing) {
        if (elements.playBtn) {
            if (playing) {
                elements.playBtn.classList.add('playing');
            } else {
                elements.playBtn.classList.remove('playing');
            }
        }
    }
    
    function loadStation(index) {
        if (index < 0 || index >= stations.length) return;
        
        // Stop current stream if playing
        if (audioElement) {
            stopStream();
        }
        
        // Update current station
        currentStationIndex = index;
        updateActiveState(index);
        
        // Fetch metadata immediately for new station
        fetchMetadata();
        
        // Create and configure audio
        audioElement = new Audio();
        audioElement.preload = 'none';
        
        // Event handlers
        audioElement.addEventListener('playing', function() {
            isPlaying = true;
            updatePlayButton(true);
            startMetadataUpdates();
        });
        
        audioElement.addEventListener('pause', function() {
            isPlaying = false;
            updatePlayButton(false);
        });
        
        audioElement.addEventListener('error', function(e) {
            console.warn('Stream error:', e);
            isPlaying = false;
            updatePlayButton(false);
            stopMetadataUpdates();
        });
        
        audioElement.addEventListener('stalled', function() {
            console.warn('Stream stalled...');
        });
        
        // Load and play
        audioElement.src = stations[index].url;
        
        var playPromise = audioElement.play();
        if (playPromise !== undefined) {
            playPromise.then(function() {
                isPlaying = true;
                updatePlayButton(true);
            }).catch(function(error) {
                console.warn('Autoplay prevented:', error);
                isPlaying = false;
                updatePlayButton(false);
            });
        }
    }
    
    function stopStream() {
        stopMetadataUpdates();
        
        if (audioElement) {
            audioElement.pause();
            audioElement.src = '';
            audioElement.load();
            audioElement = null;
        }
        isPlaying = false;
        updatePlayButton(false);
        clearTrackDisplay();
    }
    
    function togglePlayback() {
        if (isPlaying) {
            stopStream();
        } else {
            loadStation(currentStationIndex);
        }
    }
    
    // ==========================================================================
    // Event Handlers
    // ==========================================================================
    
    function handleFloppyClick(e) {
        var floppy = e.target.closest('.floppy');
        if (!floppy) return;
        
        var streamIndex = parseInt(floppy.dataset.stream, 10);
        if (!isNaN(streamIndex)) {
            loadStation(streamIndex);
        }
    }
    
    function handlePlayButtonClick(e) {
        e.preventDefault();
        togglePlayback();
    }
    
    function handleKeyDown(e) {
        // Space bar to toggle playback (only if not in input)
        if (e.code === 'Space' && !e.target.matches('input, textarea, button')) {
            e.preventDefault();
            togglePlayback();
        }
        
        // Arrow keys to navigate stations
        if (e.code === 'ArrowRight' || e.code === 'ArrowDown') {
            e.preventDefault();
            var nextIndex = (currentStationIndex + 1) % stations.length;
            loadStation(nextIndex);
        }
        
        if (e.code === 'ArrowLeft' || e.code === 'ArrowUp') {
            e.preventDefault();
            var prevIndex = (currentStationIndex - 1 + stations.length) % stations.length;
            loadStation(prevIndex);
        }
        
        // Number keys 1-5 for direct station selection
        var num = parseInt(e.key, 10);
        if (num >= 1 && num <= 5) {
            loadStation(num - 1);
        }
    }
    
    // Pause metadata updates when tab is hidden
    function handleVisibilityChange() {
        if (document.hidden) {
            stopMetadataUpdates();
        } else if (isPlaying) {
            startMetadataUpdates();
        }
    }
    
    // ==========================================================================
    // Initialization
    // ==========================================================================
    
    function cacheElements() {
        elements.playBtn = document.getElementById('playbackButton');
        elements.stationName = document.getElementById('stationName');
        elements.trackTitle = document.getElementById('trackTitle');
        elements.trackArtist = document.getElementById('trackArtist');
        elements.trackInfo = document.getElementById('trackInfo');
        elements.floppyDisks = Array.from(document.querySelectorAll('.floppy'));
        elements.html = document.documentElement;
    }
    
    function bindEvents() {
        // Floppy disk clicks
        document.addEventListener('click', function(e) {
            // Check for floppy click
            if (e.target.closest('.floppy')) {
                handleFloppyClick(e);
                return;
            }
            
            // Check for play button click
            if (e.target.closest('#playbackButton')) {
                handlePlayButtonClick(e);
                return;
            }
        });
        
        // Keyboard controls
        document.addEventListener('keydown', handleKeyDown);
        
        // Visibility change for metadata updates
        document.addEventListener('visibilitychange', handleVisibilityChange);
    }
    
    function init() {
        // Initialize stations from CONFIG
        initializeStations();
        
        cacheElements();
        bindEvents();
        
        // Set initial state (don't autoplay, just set visual state)
        updateActiveState(currentStationIndex);
        updatePlayButton(false);
    }
    
    // ==========================================================================
    // Bootstrap
    // ==========================================================================
    
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
    
    // Expose API for external use if needed
    window.vicetream = {
        loadStation: loadStation,
        togglePlayback: togglePlayback,
        getCurrentStation: function() { return currentStationIndex; },
        isPlaying: function() { return isPlaying; },
        getCurrentTrack: function() { return currentTrack; }
    };
    
})();
