(function() {
    'use strict';
    
    // ==========================================================================
    // Configuration - Loaded from environment variables
    // ==========================================================================
    
    // CONFIG_PLACEHOLDER_START - Auto-injected by build-config.js
    var CONFIG = JSON.parse(atob('eyJzdHJlYW1zIjp7IjEiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS9ncm9vdmVzYWxhZC0xMjgtbXAzIiwiMiI6Imh0dHBzOi8vdXMzLmludGVybmV0LXJhZGlvLmNvbS9wcm94eS9jcnBsYW5ldD9tcD0vc3RyZWFtIiwiMyI6Imh0dHBzOi8vaWNlMS5zb21hZm0uY29tL2JlYXRibGVuZGVyLTEyOC1tcDMiLCI0IjoiaHR0cHM6Ly9pY2UxLnNvbWFmbS5jb20vZHJvbmV6b25lLTEyOC1tcDMiLCI1IjoiaHR0cHM6Ly9pY2UxLnNvbWFmbS5jb20vN3NvdWwtMTI4LW1wMyIsIjYiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS9ib3NzYS0xMjgtbXAzIn0sImNoYW5uZWxzIjp7IjEiOiJncm9vdmVzYWxhZCIsIjIiOiJjcnBsYW5ldCIsIjMiOiJiZWF0YmxlbmRlciIsIjQiOiJkcm9uZXpvbmUiLCI1IjoiN3NvdWwiLCI2IjoiYm9zc2EifSwibGl2ZSI6eyJzdHJlYW1FbmRwb2ludCI6Imh0dHBzOi8veW91ci1zdHJlYW1pbmctc2VydmVyLmNvbS9saXZlIiwid2VicnRjU2lnbmFsaW5nU2VydmVyIjoid3NzOi8veW91ci1zaWduYWxpbmctc2VydmVyLmNvbSIsInN0b3JhZ2VLZXkiOiJ2aWNldHJlYW1fbGl2ZV9zdGF0dXMifX0='));
    // CONFIG_PLACEHOLDER_END
    
    // Station configuration will be loaded from CONFIG object (generated by build-config.js)
    var stations = [];
    
    // Initialize stations from CONFIG if available
    function initializeStations() {
        if (typeof CONFIG !== 'undefined' && CONFIG.streams && CONFIG.channels) {
            stations = [
                { 
                    name: 'Lounge', 
                    theme: 'lounge',
                    channel: CONFIG.channels[1],
                    url: CONFIG.streams[1]
                },
                { 
                    name: 'Rock', 
                    theme: 'rock',
                    channel: CONFIG.channels[2],
                    url: CONFIG.streams[2]
                },
                { 
                    name: 'Party', 
                    theme: 'party',
                    channel: CONFIG.channels[3],
                    url: CONFIG.streams[3]
                },
                { 
                    name: 'Chill', 
                    theme: 'chill',
                    channel: CONFIG.channels[4],
                    url: CONFIG.streams[4]
                },
                { 
                    name: 'Funky', 
                    theme: 'funky',
                    channel: CONFIG.channels[5],
                    url: CONFIG.streams[5]
                },
                { 
                    name: 'Bossa', 
                    theme: 'bossa',
                    channel: CONFIG.channels[6],
                    url: CONFIG.streams[6]
                }
            ];
        } else {
            console.error('CONFIG not found. Please run build-config.js to generate configuration.');
            // Fallback to empty stations - will need config to work
            stations = [
                { name: 'Lounge', theme: 'lounge', channel: '', url: '' },
                { name: 'Rock', theme: 'rock', channel: '', url: '' },
                { name: 'Party', theme: 'party', channel: '', url: '' },
                { name: 'Chill', theme: 'chill', channel: '', url: '' },
                { name: 'Funky', theme: 'funky', channel: '', url: '' },
                { name: 'Bossa', theme: 'bossa', channel: '', url: '' }
            ];
        }
    }
    
    var METADATA_UPDATE_INTERVAL = 5000; // 5 seconds
    
    // ==========================================================================
    // State
    // ==========================================================================
    
    var currentStationIndex = 0;
    var isPlaying = false;
    var audioElement = null;
    var metadataInterval = null;
    var currentTrack = { title: '', artist: '' };
    var isTransitioning = false; // Flag to prevent state conflicts during channel switch
    
    // ==========================================================================
    // DOM References (cached after init)
    // ==========================================================================
    
    var elements = {
        playBtn: null,
        stationName: null,
        trackTitle: null,
        trackArtist: null,
        trackInfo: null,
        floppyDisks: null,
        html: null
    };

    // ==========================================================================
    // Theme Management
    // ==========================================================================
    
    function setTheme(themeName) {
        elements.html.setAttribute('data-theme', themeName);
    }
    
    function updateActiveState(index) {
        // Remove active class from all disks
        elements.floppyDisks.forEach(function(disk) {
            disk.classList.remove('active');
        });
        
        // Add active class to selected disk
        if (elements.floppyDisks[index]) {
            elements.floppyDisks[index].classList.add('active');
        }
        
        // Update station name display
        if (elements.stationName) {
            elements.stationName.textContent = stations[index].name;
        }
        
        // Update theme
        setTheme(stations[index].theme);
}

    // ==========================================================================
    // Metadata Fetching (SomaFM API)
    // ==========================================================================
    
    function fetchMetadata() {
        var station = stations[currentStationIndex];
        
        // Skip metadata fetching if no channel ID
        if (!station.channel) {
            console.log('No channel ID for this station - skipping metadata fetch');
            updateTrackDisplay('Now Playing', station.name);
            return;
        }
        
        // Detect source type and fetch accordingly
        if (station.url.includes('somafm.com')) {
            fetchSomaFMMetadata(station);
        } else if (station.url.includes('internet-radio.com')) {
            fetchInternetRadioMetadata(station);
        } else {
            // Generic fallback
            updateTrackDisplay('Now Playing', station.name);
}
    }
    
    function fetchSomaFMMetadata(station) {
        var apiUrl = 'https://somafm.com/songs/' + station.channel + '.json';
        
        fetch(apiUrl)
            .then(function(response) {
                if (!response.ok) throw new Error('Network response was not ok');
                return response.json();
            })
            .then(function(data) {
                if (data && data.songs && data.songs.length > 0) {
                    var song = data.songs[0]; // Most recent song
                    updateTrackDisplay(song.title, song.artist);
                }
            })
            .catch(function(error) {
                console.warn('Failed to fetch SomaFM metadata:', error);
            });
    }
    
    function fetchInternetRadioMetadata(station) {
        // Fetch the station page and get metadata from the specific span element
        // First fetch might return cached data, so we'll fetch again after 2 seconds
        
        function doFetch(isFreshFetch) {
            var timestamp = new Date().getTime();
            var stationUrl = 'https://www.internet-radio.com/station/' + station.channel + '/?_=' + timestamp;
            var corsProxy = 'https://corsproxy.io/?';
            var proxiedUrl = corsProxy + encodeURIComponent(stationUrl);
            
            if (isFreshFetch) {
                console.log('Fetching fresh metadata (2nd attempt)...');
            }
            
            fetch(proxiedUrl, { 
                cache: 'no-cache',
                headers: {
                    'Cache-Control': 'no-cache',
                    'Pragma': 'no-cache'
                }
            })
                .then(function(response) {
                    if (!response.ok) throw new Error('HTTP ' + response.status);
                    return response.text();
                })
                .then(function(html) {
                    // Parse HTML
                    var parser = new DOMParser();
                    var doc = parser.parseFromString(html, 'text/html');
                    
                    // Target the specific span element: <span id="cc_strinfo_song_crplanet" class="cc_streaminfo">
                    var metadataElement = doc.getElementById('cc_strinfo_song_' + station.channel);
                    
                    if (metadataElement) {
                        var trackInfo = metadataElement.textContent.trim();
                        console.log('Found metadata' + (isFreshFetch ? ' (fresh)' : '') + ':', trackInfo);
                        
                        // Split by " - " to get artist and title
                        if (trackInfo && trackInfo.includes(' - ')) {
                            var parts = trackInfo.split(' - ');
                            var artist = parts[0].trim();
                            var title = parts.slice(1).join(' - ').trim();
                            updateTrackDisplay(title, artist);
                            return;
                        } else if (trackInfo) {
                            updateTrackDisplay(trackInfo, station.name);
                            return;
                        }
                    }
                    
                    // Fallback: try the old XPath location
                    var fallbackElement = doc.querySelector('body > div:first-of-type > div > div:first-of-type > p > b > span');
                    if (fallbackElement) {
                        var trackInfo = fallbackElement.textContent.trim();
                        console.log('Found metadata from fallback location' + (isFreshFetch ? ' (fresh)' : '') + ':', trackInfo);
                        
                        if (trackInfo && trackInfo.includes(' - ')) {
                            var parts = trackInfo.split(' - ');
                            updateTrackDisplay(parts.slice(1).join(' - ').trim(), parts[0].trim());
                        } else if (trackInfo) {
                            updateTrackDisplay(trackInfo, station.name);
                        }
                        return;
                    }
                    
                    if (!isFreshFetch) {
                        console.warn('Could not find metadata element on first try');
                    } else {
                        console.warn('Could not find metadata element');
                        updateTrackDisplay('Classic Rock', station.name);
                    }
                })
                .catch(function(error) {
                    console.error('Metadata fetch failed:', error.message);
                    if (isFreshFetch) {
                        updateTrackDisplay('Classic Rock', station.name);
                    }
                });
        }
        
        // First fetch (might be cached)
        doFetch(false);
        
        // Second fetch after 2 seconds (should be fresh)
        setTimeout(function() {
            // Only fetch again if we're still on the same station
            if (stations[currentStationIndex].channel === station.channel && isPlaying) {
                doFetch(true);
            }
        }, 2000);
    }
    
    function updateTrackDisplay(title, artist) {
        // Only update if something changed
        if (title === currentTrack.title && artist === currentTrack.artist) {
            return;
        }
        
        currentTrack.title = title || '';
        currentTrack.artist = artist || '';
        
        if (elements.trackTitle) {
            elements.trackTitle.textContent = currentTrack.title || '—';
            // Add animation class
            elements.trackTitle.classList.remove('track-update');
            void elements.trackTitle.offsetWidth; // Trigger reflow
            elements.trackTitle.classList.add('track-update');
        }
        
        if (elements.trackArtist) {
            elements.trackArtist.textContent = currentTrack.artist;
            elements.trackArtist.classList.remove('track-update');
            void elements.trackArtist.offsetWidth;
            elements.trackArtist.classList.add('track-update');
    }
        
        // Update page title with now playing
        if (isPlaying && currentTrack.title) {
            document.title = currentTrack.title + ' - ' + stations[currentStationIndex].name + ' | Vicetream';
        }
    }
    
    function clearTrackDisplay() {
        currentTrack = { title: '', artist: '' };
        if (elements.trackTitle) {
            elements.trackTitle.textContent = '—';
        }
        if (elements.trackArtist) {
            elements.trackArtist.textContent = '';
        }
        document.title = 'Vicetream Tunes';
    }
    
    function startMetadataUpdates() {
        // Fetch immediately
        fetchMetadata();
        
        // Then fetch periodically
        if (metadataInterval) {
            clearInterval(metadataInterval);
        }
        metadataInterval = setInterval(fetchMetadata, METADATA_UPDATE_INTERVAL);
    }
    
    function stopMetadataUpdates() {
        if (metadataInterval) {
            clearInterval(metadataInterval);
            metadataInterval = null;
        }
    }
    
    // ==========================================================================
    // Audio Playback
    // ==========================================================================
    
    function updatePlayButton(playing) {
        if (elements.playBtn) {
            if (playing) {
                elements.playBtn.classList.add('playing');
            } else {
                elements.playBtn.classList.remove('playing');
            }
        }
    }
    
    function loadStation(index) {
        if (index < 0 || index >= stations.length) return;
        
        // Set transition flag
        isTransitioning = true;
        
        // Stop current stream if playing (silent cleanup)
        if (audioElement) {
            stopMetadataUpdates();
            
            // Remove all event listeners by cloning (prevents old events from firing)
            var oldAudio = audioElement;
            oldAudio.pause();
            oldAudio.src = '';
            oldAudio.load();
            audioElement = null;
        }
        
        // Update current station immediately
        currentStationIndex = index;
        updateActiveState(index);
        
        // Fetch metadata immediately for new station
        fetchMetadata();
        
        // Create and configure new audio element
        audioElement = new Audio();
        audioElement.preload = 'none';
        
        // Store reference for closure
        var currentAudio = audioElement;
        
        // Event handlers with transition guard
        audioElement.addEventListener('playing', function() {
            // Only update if this is still the current audio element
            if (currentAudio === audioElement && !isTransitioning) {
                isPlaying = true;
                updatePlayButton(true);
                startMetadataUpdates();
            }
        });
        
        audioElement.addEventListener('pause', function() {
            // Only update if this is still the current audio element and not transitioning
            if (currentAudio === audioElement && !isTransitioning) {
                isPlaying = false;
                updatePlayButton(false);
            }
        });
        
        audioElement.addEventListener('error', function(e) {
            // Only update if this is still the current audio element
            if (currentAudio === audioElement) {
                console.warn('Stream error:', e);
                isPlaying = false;
                updatePlayButton(false);
                stopMetadataUpdates();
                isTransitioning = false;
            }
        });
        
        audioElement.addEventListener('stalled', function() {
            console.warn('Stream stalled...');
        });
        
        // Load and play
        audioElement.src = stations[index].url;
        
        var playPromise = audioElement.play();
        if (playPromise !== undefined) {
            playPromise.then(function() {
                // Clear transition flag once playback starts
                isTransitioning = false;
                if (currentAudio === audioElement) {
                    isPlaying = true;
                    updatePlayButton(true);
                }
            }).catch(function(error) {
                console.warn('Autoplay prevented:', error);
                isTransitioning = false;
                if (currentAudio === audioElement) {
                    isPlaying = false;
                    updatePlayButton(false);
                }
            });
        } else {
            isTransitioning = false;
        }
    }
    
    function stopStream() {
        stopMetadataUpdates();
        
        if (audioElement) {
            audioElement.pause();
            audioElement.src = '';
            audioElement.load();
            audioElement = null;
        }
        
        isPlaying = false;
        isTransitioning = false;
        updatePlayButton(false);
        clearTrackDisplay();
    }
    
    function togglePlayback() {
        if (isPlaying) {
            stopStream();
        } else {
            loadStation(currentStationIndex);
        }
    }
    
    // ==========================================================================
    // Event Handlers
    // ==========================================================================
    
    function handleFloppyClick(e) {
        var floppy = e.target.closest('.floppy');
        if (!floppy) return;
        
        var streamIndex = parseInt(floppy.dataset.stream, 10);
        if (!isNaN(streamIndex)) {
            loadStation(streamIndex);
        }
    }
    
    function handlePlayButtonClick(e) {
        e.preventDefault();
        togglePlayback();
    }
    
    function handleKeyDown(e) {
        // Space bar to toggle playback (only if not in input)
        if (e.code === 'Space' && !e.target.matches('input, textarea, button')) {
            e.preventDefault();
            togglePlayback();
        }
        
        // Arrow keys to navigate stations
        if (e.code === 'ArrowRight' || e.code === 'ArrowDown') {
            e.preventDefault();
            var nextIndex = (currentStationIndex + 1) % stations.length;
            loadStation(nextIndex);
        }
        
        if (e.code === 'ArrowLeft' || e.code === 'ArrowUp') {
            e.preventDefault();
            var prevIndex = (currentStationIndex - 1 + stations.length) % stations.length;
            loadStation(prevIndex);
        }
        
        // Number keys 1-5 for direct station selection
        var num = parseInt(e.key, 10);
        if (num >= 1 && num <= 5) {
            loadStation(num - 1);
        }
    }
    
    // Pause metadata updates when tab is hidden
    function handleVisibilityChange() {
        if (document.hidden) {
            stopMetadataUpdates();
        } else if (isPlaying) {
            startMetadataUpdates();
        }
    }
    
    // ==========================================================================
    // Initialization
    // ==========================================================================
    
    function cacheElements() {
        elements.playBtn = document.getElementById('playbackButton');
        elements.stationName = document.getElementById('stationName');
        elements.trackTitle = document.getElementById('trackTitle');
        elements.trackArtist = document.getElementById('trackArtist');
        elements.trackInfo = document.getElementById('trackInfo');
        elements.floppyDisks = Array.from(document.querySelectorAll('.floppy'));
        elements.html = document.documentElement;
    }
    
    function bindEvents() {
        // Floppy disk clicks
        document.addEventListener('click', function(e) {
            // Check for floppy click
            if (e.target.closest('.floppy')) {
                handleFloppyClick(e);
                return;
            }
            
            // Check for play button click
            if (e.target.closest('#playbackButton')) {
                handlePlayButtonClick(e);
                return;
            }
        });
        
        // Keyboard controls
        document.addEventListener('keydown', handleKeyDown);
        
        // Visibility change for metadata updates
        document.addEventListener('visibilitychange', handleVisibilityChange);
    }
    
    function init() {
        // Initialize stations from CONFIG
        initializeStations();
        
        cacheElements();
        bindEvents();
        
        // Set initial state (don't autoplay, just set visual state)
        updateActiveState(currentStationIndex);
        updatePlayButton(false);
    }
    
    // ==========================================================================
    // Bootstrap
    // ==========================================================================
    
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
    
    // Expose API for external use if needed
    window.vicetream = {
        loadStation: loadStation,
        togglePlayback: togglePlayback,
        getCurrentStation: function() { return currentStationIndex; },
        isPlaying: function() { return isPlaying; },
        getCurrentTrack: function() { return currentTrack; }
    };
    
})();
