(function() {
    'use strict';
    
    // ==========================================================================
    // Configuration - Loaded from environment variables
    // ==========================================================================
    
    // Station configuration will be loaded from CONFIG object (generated by build-config.js)
    var stations = [];
    
    // Initialize stations from CONFIG if available
    function initializeStations() {
        if (typeof CONFIG !== 'undefined' && CONFIG.streams && CONFIG.channels) {
            stations = [
                { 
                    name: 'Lounge', 
                    theme: 'lounge',
                    channel: CONFIG.channels[1],
                    url: CONFIG.streams[1]
                },
                { 
                    name: 'Cool', 
                    theme: 'cool',
                    channel: CONFIG.channels[2],
                    url: CONFIG.streams[2]
                },
                { 
                    name: 'Rock', 
                    theme: 'rock',
                    channel: CONFIG.channels[3],
                    url: CONFIG.streams[3]
                },
                { 
                    name: 'Party', 
                    theme: 'party',
                    channel: CONFIG.channels[4],
                    url: CONFIG.streams[4]
                },
                { 
                    name: 'Chill', 
                    theme: 'chill',
                    channel: CONFIG.channels[5],
                    url: CONFIG.streams[5]
                }
            ];
        } else {
            console.error('CONFIG not found. Please run build-config.js to generate configuration.');
            // Fallback to empty stations - will need config to work
            stations = [
                { name: 'Lounge', theme: 'lounge', channel: '', url: '' },
                { name: 'Cool', theme: 'cool', channel: '', url: '' },
                { name: 'Rock', theme: 'rock', channel: '', url: '' },
                { name: 'Party', theme: 'party', channel: '', url: '' },
                { name: 'Chill', theme: 'chill', channel: '', url: '' }
            ];
        }
    }
    
    var METADATA_UPDATE_INTERVAL = 20000; // 20 seconds
    
    // ==========================================================================
    // State
    // ==========================================================================
    
    var currentStationIndex = 0;
    var isPlaying = false;
    var audioElement = null;
    var metadataInterval = null;
    var currentTrack = { title: '', artist: '' };
    
    // ==========================================================================
    // DOM References (cached after init)
    // ==========================================================================
    
    var elements = {
        playBtn: null,
        stationName: null,
        trackTitle: null,
        trackArtist: null,
        trackInfo: null,
        floppyDisks: null,
        html: null
    };
    
    // ==========================================================================
    // Theme Management
    // ==========================================================================
    
    function setTheme(themeName) {
        elements.html.setAttribute('data-theme', themeName);
    }
    
    function updateActiveState(index) {
        // Remove active class from all disks
        elements.floppyDisks.forEach(function(disk) {
            disk.classList.remove('active');
        });
        
        // Add active class to selected disk
        if (elements.floppyDisks[index]) {
            elements.floppyDisks[index].classList.add('active');
        }
        
        // Update station name display
        if (elements.stationName) {
            elements.stationName.textContent = stations[index].name;
        }
        
        // Update theme
        setTheme(stations[index].theme);
    }
    
    // ==========================================================================
    // Metadata Fetching (SomaFM API)
    // ==========================================================================
    
    function fetchMetadata() {
        var station = stations[currentStationIndex];
        
        // Skip metadata fetching if no channel ID
        if (!station.channel) {
            console.log('No channel ID for this station - skipping metadata fetch');
            updateTrackDisplay('Now Playing', station.name);
            return;
        }
        
        // Detect source type and fetch accordingly
        if (station.url.includes('internet-radio.com')) {
            fetchInternetRadioMetadata(station);
        } else if (station.url.includes('somafm.com')) {
            fetchSomaFMMetadata(station);
        } else {
            // Generic fallback
            updateTrackDisplay('Now Playing', station.name);
        }
    }
    
    function fetchSomaFMMetadata(station) {
        var apiUrl = 'https://somafm.com/songs/' + station.channel + '.json';
        
        fetch(apiUrl)
            .then(function(response) {
                if (!response.ok) throw new Error('Network response was not ok');
                return response.json();
            })
            .then(function(data) {
                if (data && data.songs && data.songs.length > 0) {
                    var song = data.songs[0]; // Most recent song
                    updateTrackDisplay(song.title, song.artist);
                }
            })
            .catch(function(error) {
                console.warn('Failed to fetch SomaFM metadata:', error);
            });
    }
    
    function fetchInternetRadioMetadata(station) {
        // Try to fetch from internet-radio.com station page
        var stationUrl = 'https://www.internet-radio.com/station/' + station.channel + '/';
        
        // Use a CORS proxy or direct fetch
        fetch(stationUrl)
            .then(function(response) {
                if (!response.ok) throw new Error('Network response was not ok');
                return response.text();
            })
            .then(function(html) {
                // Parse the HTML to extract "Now Playing" info
                var parser = new DOMParser();
                var doc = parser.parseFromString(html, 'text/html');
                
                // Look for the "Now Playing" text pattern
                var bodyText = doc.body.textContent || doc.body.innerText || '';
                var nowPlayingMatch = bodyText.match(/Now Playing\s*:\s*\*\*([^*]+)\*\*/);
                
                if (nowPlayingMatch && nowPlayingMatch[1]) {
                    var trackInfo = nowPlayingMatch[1].trim();
                    // Split by common separators: " - ", " – ", " — "
                    var parts = trackInfo.split(/\s*[-–—]\s*/);
                    
                    if (parts.length >= 2) {
                        var artist = parts[0].trim();
                        var title = parts.slice(1).join(' - ').trim();
                        updateTrackDisplay(title, artist);
                    } else {
                        updateTrackDisplay(trackInfo, station.name);
                    }
                } else {
                    updateTrackDisplay('Now Playing', station.name);
                }
            })
            .catch(function(error) {
                console.warn('Failed to fetch Internet Radio metadata:', error);
                console.warn('CORS might be blocking the request. Showing station name instead.');
                updateTrackDisplay('Now Playing', station.name);
            });
    }
    
    function updateTrackDisplay(title, artist) {
        // Only update if something changed
        if (title === currentTrack.title && artist === currentTrack.artist) {
            return;
        }
        
        currentTrack.title = title || '';
        currentTrack.artist = artist || '';
        
        if (elements.trackTitle) {
            elements.trackTitle.textContent = currentTrack.title || '—';
            // Add animation class
            elements.trackTitle.classList.remove('track-update');
            void elements.trackTitle.offsetWidth; // Trigger reflow
            elements.trackTitle.classList.add('track-update');
        }
        
        if (elements.trackArtist) {
            elements.trackArtist.textContent = currentTrack.artist;
            elements.trackArtist.classList.remove('track-update');
            void elements.trackArtist.offsetWidth;
            elements.trackArtist.classList.add('track-update');
        }
        
        // Update page title with now playing
        if (isPlaying && currentTrack.title) {
            document.title = currentTrack.title + ' - ' + stations[currentStationIndex].name + ' | Vicetream';
        }
    }
    
    function clearTrackDisplay() {
        currentTrack = { title: '', artist: '' };
        if (elements.trackTitle) {
            elements.trackTitle.textContent = '—';
        }
        if (elements.trackArtist) {
            elements.trackArtist.textContent = '';
        }
        document.title = 'Vicetream Tunes';
    }
    
    function startMetadataUpdates() {
        // Fetch immediately
        fetchMetadata();
        
        // Then fetch periodically
        if (metadataInterval) {
            clearInterval(metadataInterval);
        }
        metadataInterval = setInterval(fetchMetadata, METADATA_UPDATE_INTERVAL);
    }
    
    function stopMetadataUpdates() {
        if (metadataInterval) {
            clearInterval(metadataInterval);
            metadataInterval = null;
        }
    }
    
    // ==========================================================================
    // Audio Playback
    // ==========================================================================
    
    function updatePlayButton(playing) {
        if (elements.playBtn) {
            if (playing) {
                elements.playBtn.classList.add('playing');
            } else {
                elements.playBtn.classList.remove('playing');
            }
        }
    }
    
    function loadStation(index) {
        if (index < 0 || index >= stations.length) return;
        
        // Stop current stream if playing
        if (audioElement) {
            stopStream();
        }
        
        // Update current station
        currentStationIndex = index;
        updateActiveState(index);
        
        // Create and configure audio
        audioElement = new Audio();
        audioElement.preload = 'none';
        
        // Event handlers
        audioElement.addEventListener('playing', function() {
            isPlaying = true;
            updatePlayButton(true);
            startMetadataUpdates();
        });
        
        audioElement.addEventListener('pause', function() {
            isPlaying = false;
            updatePlayButton(false);
        });
        
        audioElement.addEventListener('error', function(e) {
            console.warn('Stream error:', e);
            isPlaying = false;
            updatePlayButton(false);
            stopMetadataUpdates();
        });
        
        audioElement.addEventListener('stalled', function() {
            console.warn('Stream stalled...');
        });
        
        // Load and play
        audioElement.src = stations[index].url;
        
        var playPromise = audioElement.play();
        if (playPromise !== undefined) {
            playPromise.then(function() {
                isPlaying = true;
                updatePlayButton(true);
            }).catch(function(error) {
                console.warn('Autoplay prevented:', error);
                isPlaying = false;
                updatePlayButton(false);
            });
        }
    }
    
    function stopStream() {
        stopMetadataUpdates();
        
        if (audioElement) {
            audioElement.pause();
            audioElement.src = '';
            audioElement.load();
            audioElement = null;
        }
        isPlaying = false;
        updatePlayButton(false);
        clearTrackDisplay();
    }
    
    function togglePlayback() {
        if (isPlaying) {
            stopStream();
        } else {
            loadStation(currentStationIndex);
        }
    }
    
    // ==========================================================================
    // Event Handlers
    // ==========================================================================
    
    function handleFloppyClick(e) {
        var floppy = e.target.closest('.floppy');
        if (!floppy) return;
        
        var streamIndex = parseInt(floppy.dataset.stream, 10);
        if (!isNaN(streamIndex)) {
            loadStation(streamIndex);
        }
    }
    
    function handlePlayButtonClick(e) {
        e.preventDefault();
        togglePlayback();
    }
    
    function handleKeyDown(e) {
        // Space bar to toggle playback (only if not in input)
        if (e.code === 'Space' && !e.target.matches('input, textarea, button')) {
            e.preventDefault();
            togglePlayback();
        }
        
        // Arrow keys to navigate stations
        if (e.code === 'ArrowRight' || e.code === 'ArrowDown') {
            e.preventDefault();
            var nextIndex = (currentStationIndex + 1) % stations.length;
            loadStation(nextIndex);
        }
        
        if (e.code === 'ArrowLeft' || e.code === 'ArrowUp') {
            e.preventDefault();
            var prevIndex = (currentStationIndex - 1 + stations.length) % stations.length;
            loadStation(prevIndex);
        }
        
        // Number keys 1-5 for direct station selection
        var num = parseInt(e.key, 10);
        if (num >= 1 && num <= 5) {
            loadStation(num - 1);
        }
    }
    
    // Pause metadata updates when tab is hidden
    function handleVisibilityChange() {
        if (document.hidden) {
            stopMetadataUpdates();
        } else if (isPlaying) {
            startMetadataUpdates();
        }
    }
    
    // ==========================================================================
    // Initialization
    // ==========================================================================
    
    function cacheElements() {
        elements.playBtn = document.getElementById('playbackButton');
        elements.stationName = document.getElementById('stationName');
        elements.trackTitle = document.getElementById('trackTitle');
        elements.trackArtist = document.getElementById('trackArtist');
        elements.trackInfo = document.getElementById('trackInfo');
        elements.floppyDisks = Array.from(document.querySelectorAll('.floppy'));
        elements.html = document.documentElement;
    }
    
    function bindEvents() {
        // Floppy disk clicks
        document.addEventListener('click', function(e) {
            // Check for floppy click
            if (e.target.closest('.floppy')) {
                handleFloppyClick(e);
                return;
            }
            
            // Check for play button click
            if (e.target.closest('#playbackButton')) {
                handlePlayButtonClick(e);
                return;
            }
        });
        
        // Keyboard controls
        document.addEventListener('keydown', handleKeyDown);
        
        // Visibility change for metadata updates
        document.addEventListener('visibilitychange', handleVisibilityChange);
    }
    
    function init() {
        // Initialize stations from CONFIG
        initializeStations();
        
        cacheElements();
        bindEvents();
        
        // Set initial state (don't autoplay, just set visual state)
        updateActiveState(currentStationIndex);
        updatePlayButton(false);
    }
    
    // ==========================================================================
    // Bootstrap
    // ==========================================================================
    
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
    
    // Expose API for external use if needed
    window.vicetream = {
        loadStation: loadStation,
        togglePlayback: togglePlayback,
        getCurrentStation: function() { return currentStationIndex; },
        isPlaying: function() { return isPlaying; },
        getCurrentTrack: function() { return currentTrack; }
    };
    
})();
