(function() {
    'use strict';
    
    // ==========================================================================
    // Configuration - Loaded from environment variables
    // ==========================================================================
    
    // CONFIG_PLACEHOLDER_START - Auto-injected by build-config.js
    var CONFIG = JSON.parse(atob('eyJzdHJlYW1zIjp7IjEiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS9ncm9vdmVzYWxhZC0xMjgtbXAzIiwiMiI6Imh0dHBzOi8vdXMzLmludGVybmV0LXJhZGlvLmNvbS9wcm94eS9jcnBsYW5ldD9tcD0vc3RyZWFtIiwiMyI6Imh0dHBzOi8vaWNlMS5zb21hZm0uY29tL2JlYXRibGVuZGVyLTEyOC1tcDMiLCI0IjoiaHR0cHM6Ly9pY2UxLnNvbWFmbS5jb20vZHJvbmV6b25lLTEyOC1tcDMiLCI1IjoiaHR0cHM6Ly9pY2UxLnNvbWFmbS5jb20vN3NvdWwtMTI4LW1wMyIsIjYiOiJodHRwczovL2ljZTEuc29tYWZtLmNvbS9ib3NzYS0xMjgtbXAzIn0sImNoYW5uZWxzIjp7IjEiOiJncm9vdmVzYWxhZCIsIjIiOiJjcnBsYW5ldCIsIjMiOiJiZWF0YmxlbmRlciIsIjQiOiJkcm9uZXpvbmUiLCI1IjoiN3NvdWwiLCI2IjoiYm9zc2EifSwibGl2ZSI6eyJzdHJlYW1FbmRwb2ludCI6Imh0dHBzOi8veW91ci1zdHJlYW1pbmctc2VydmVyLmNvbS9saXZlIiwid2VicnRjU2lnbmFsaW5nU2VydmVyIjoid3NzOi8veW91ci1zaWduYWxpbmctc2VydmVyLmNvbSIsInN0b3JhZ2VLZXkiOiJ2aWNldHJlYW1fbGl2ZV9zdGF0dXMifX0='));
    // CONFIG_PLACEHOLDER_END
    
    // Live configuration will be loaded from CONFIG object (generated by build-config.js)
    let LIVE_STATUS_KEY = 'vicetream_live_status';
    let LIVE_STREAM_KEY = 'vicetream_live_stream';
    let LIVE_DJ_NAME_KEY = 'vicetream_dj_name';
    let LIVE_STREAM_ENDPOINT = '';
    let LIVE_WEBRTC_SERVER = '';
    
    // Initialize live config from CONFIG if available
    function initializeLiveConfig() {
        if (typeof CONFIG !== 'undefined' && CONFIG.live) {
            LIVE_STATUS_KEY = CONFIG.live.storageKey || LIVE_STATUS_KEY;
            LIVE_STREAM_KEY = CONFIG.live.storageKey + '_stream' || LIVE_STREAM_KEY;
            LIVE_DJ_NAME_KEY = CONFIG.live.storageKey + '_dj_name' || LIVE_DJ_NAME_KEY;
            LIVE_STREAM_ENDPOINT = CONFIG.live.streamEndpoint || '';
            LIVE_WEBRTC_SERVER = CONFIG.live.webrtcSignalingServer || '';
        } else {
            console.warn('CONFIG not found. Using default settings.');
        }
    }
    
    // ==========================================================================
    // DOM Elements
    // ==========================================================================
    
    const elements = {
        liveFeed: null,
        liveAudio: null,
        emptyStage: null,
        statusBadge: null,
        statusText: null,
        djName: null,
        djNameText: null,
        backBtn: null,
        equalizer: null,
        eqBars: null
    };
    
    // ==========================================================================
    // State
    // ==========================================================================
    
    let state = {
        isLive: false,
        audioContext: null,
        analyser: null,
        animationFrameId: null,
        checkInterval: null
    };
    
    // ==========================================================================
    // Initialization
    // ==========================================================================
    
    function init() {
        cacheElements();
        checkLiveStatus();
        
        // Check for live status every 10 seconds
        state.checkInterval = setInterval(checkLiveStatus, 10000);
    }
    
    function cacheElements() {
        elements.liveFeed = document.getElementById('liveFeed');
        elements.liveAudio = document.getElementById('liveAudio');
        elements.emptyStage = document.getElementById('emptyStage');
        elements.statusBadge = document.getElementById('statusBadge');
        elements.statusText = elements.statusBadge?.querySelector('.stage-status-text');
        elements.djName = document.getElementById('djName');
        elements.djNameText = document.getElementById('djNameText');
        elements.backBtn = document.getElementById('backBtn');
        elements.equalizer = document.getElementById('equalizer');
        elements.eqBars = elements.equalizer?.querySelectorAll('.stage-eq-bar');
    }
    
    // ==========================================================================
    // Check Live Status
    // ==========================================================================
    
    function checkLiveStatus() {
        // In production, this would be an API call
        // For demo purposes, checking localStorage
        const isLive = localStorage.getItem(LIVE_STATUS_KEY) === 'true';
        
        if (isLive) {
            const streamUrl = localStorage.getItem(LIVE_STREAM_KEY);
            const djName = localStorage.getItem(LIVE_DJ_NAME_KEY) || 'Live DJ';
            showLivePerformance(streamUrl, djName);
        } else {
            showEmptyStage();
        }
    }
    
    // ==========================================================================
    // Show Empty Stage
    // ==========================================================================
    
    function showEmptyStage() {
        if (state.isLive) {
            stopViewing();
        }
        
        state.isLive = false;
        elements.emptyStage.style.display = 'flex';
        elements.backBtn.style.display = 'none';
        elements.djName.style.display = 'none';
        elements.statusBadge.classList.remove('live');
        elements.statusText.textContent = 'OFFLINE';
    }
    
    // ==========================================================================
    // Show Live Performance
    // ==========================================================================
    
    function showLivePerformance(streamUrl, djName) {
        if (state.isLive) return; // Already viewing
        
        state.isLive = true;
        
        // Hide empty stage
        elements.emptyStage.style.display = 'none';
        elements.backBtn.style.display = 'flex';
        
        // Show DJ name
        elements.djName.style.display = 'block';
        elements.djNameText.textContent = djName;
        
        // Update status
        elements.statusBadge.classList.add('live');
        elements.statusText.textContent = 'LIVE';
        
        // Load audio stream
        if (streamUrl) {
            elements.liveAudio.src = streamUrl;
            elements.liveAudio.play().catch(err => {
                console.warn('Autoplay blocked:', err);
            });
            
            // Initialize visualizer
            initAudioVisualizer();
        }
        
        // Note: In a real app, you'd connect to a WebRTC stream or similar
        // for the camera feed. For now, we'll just show the overlay.
    }
    
    // ==========================================================================
    // Stop Viewing
    // ==========================================================================
    
    function stopViewing() {
        // Stop audio
        elements.liveAudio.pause();
        elements.liveAudio.src = '';
        
        // Stop visualizer
        stopAudioVisualizer();
    }
    
    // ==========================================================================
    // Audio Visualizer
    // ==========================================================================
    
    function initAudioVisualizer() {
        try {
            const AudioContextClass = window.AudioContext || window.webkitAudioContext;
            state.audioContext = new AudioContextClass();
            
            state.analyser = state.audioContext.createAnalyser();
            state.analyser.fftSize = 256;
            state.analyser.smoothingTimeConstant = 0.8;
            
            const source = state.audioContext.createMediaElementSource(elements.liveAudio);
            source.connect(state.analyser);
            state.analyser.connect(state.audioContext.destination);
            
            visualize();
        } catch (error) {
            console.error('Failed to initialize visualizer:', error);
        }
    }
    
    function visualize() {
        if (!state.isLive || !state.analyser) return;
        
        const bufferLength = state.analyser.frequencyBinCount;
        const dataArray = new Uint8Array(bufferLength);
        
        function draw() {
            if (!state.isLive) return;
            
            state.animationFrameId = requestAnimationFrame(draw);
            state.analyser.getByteFrequencyData(dataArray);
            
            const barsCount = elements.eqBars.length;
            const step = Math.floor(bufferLength / barsCount);
            
            elements.eqBars.forEach((bar, index) => {
                const value = dataArray[index * step];
                const percent = value / 255;
                const height = 30 + (percent * 70);
                bar.style.height = height + 'px';
            });
        }
        
        draw();
    }
    
    function stopAudioVisualizer() {
        if (state.animationFrameId) {
            cancelAnimationFrame(state.animationFrameId);
            state.animationFrameId = null;
        }
        
        if (state.audioContext) {
            state.audioContext.close();
            state.audioContext = null;
            state.analyser = null;
        }
        
        elements.eqBars?.forEach(bar => {
            bar.style.height = '30px';
        });
    }
    
    // ==========================================================================
    // Cleanup
    // ==========================================================================
    
    window.addEventListener('beforeunload', () => {
        if (state.checkInterval) {
            clearInterval(state.checkInterval);
        }
        stopViewing();
    });
    
    // ==========================================================================
    // Bootstrap
    // ==========================================================================
    
    function bootstrap() {
        initializeLiveConfig();
        init();
    }
    
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', bootstrap);
    } else {
        bootstrap();
    }
    
})();
